# Generated by Django 4.2.23 on 2025-08-14 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banners',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banner_image', models.ImageField(max_length=255, upload_to='banner/')),
                ('banner_text1', models.CharField(blank=True, max_length=100, null=True)),
                ('banner_text2', models.CharField(blank=True, max_length=250, null=True)),
                ('banner_text3', models.TextField(blank=True, null=True)),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
            ],
        ),
        migrations.CreateModel(
            name='NewsEvents',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('status', models.IntegerField(choices=[(0, 'Inactive'), (1, 'Active')], default=1)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/')),
            ],
        ),
    ]
