# Generated by Django 4.2.23 on 2025-08-14 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='marital_status',
            field=models.CharField(blank=True, choices=[('Single', 'Single'), ('Divorced', 'Divorced')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='star',
            field=models.CharField(blank=True, choices=[('Aswathi', 'Aswathi'), ('Bharani', 'Bharani'), ('Karthika', 'Karthika'), ('Rohini', 'Rohini'), ('Makayiram', 'Makayiram'), ('Thiruvathira', 'Thiruvathira'), ('Punartham', 'Punartham'), ('Pooyam', 'Pooyam'), ('Aayilyam', 'Aayilyam'), ('Makam', 'Makam'), ('Pooram', 'Pooram'), ('Uthram', 'Uthram'), ('Atham', 'Atham'), ('Chittira', 'Chittira'), ('Chothi', 'Chothi'), ('Vishakam', 'Vishakam'), ('Anizham', 'Anizham'), ('Thiruketta', 'Thiruketta'), ('Moolam', 'Moolam'), ('Pooradam', 'Pooradam'), ('Uthradam', 'Uthradam'), ('Thiruvonam', 'Thiruvonam'), ('Avittam', 'Avittam'), ('Chathayam', 'Chathayam'), ('Pooruruttathi', 'Pooruruttathi'), ('Uthrattathi', 'Uthrattathi'), ('Revathi', 'Revathi')], max_length=50, null=True),
        ),
    ]
