# Generated by Django 4.2.23 on 2025-08-14 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_payment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='star',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
